name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Run Spotless Check
        run: ./gradlew spotlessCheck

  build:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
     - name: Check out the repo
       uses: actions/checkout@v2
     
     - uses: actions/cache@v2
       with:
        path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
            ${{ runner.os }}-gradle-
       
     - name: Compile and build image
       run: ./gradlew bootBuildImage --imageName=daniloleemes/wishlisted-server

     - name: Push Docker image
       run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push daniloleemes/wishlisted-server:latest
       env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
   needs: [build]
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v2
         
     - name: Upload docker-compose.yml
       uses: appleboy/scp-action@master
       with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.yml"
          target: "~"

     - name: Login to Host and deploy docker
       uses: fifsky/ssh-action@v0.0.3
       with:
         host: ${{ secrets.HOST }}
         user: ${{ secrets.USERNAME }}
         key: ${{ secrets.SSH_KEY }}
         command: docker-compose down && docker pull daniloleemes/wishlisted-server && docker-compose up -d
